### ISSUE TITLE
Connectivity issues with LCD/RPC

### ISSUE THREAD

**Issue by steevi** [alexanderbez/juno#21]
I'm experimenting with cosmos, and I'm having some issue connecting to the RPC and LCD endpoints.

If I curl both LCD and RPC endpoints I get a reply from the network, but when I use the following `config.toml` to connect to the network I get the following error

`{"level":"info","error":"Validators: response error: RPC error -32603 - Internal error: height must be greater than 0","height":83,"time":"2020-02-27T17:07:48Z","message":"failed to get validators for block"}`

```
config.toml
rpc_node = "http://127.0.0.1:26657"
client_node = "http://127.0.0.1:1317"

[database]
host = "localhost"
port = 5432
name = "postgredb"
user = "admin"
password = "password"
ssl_mode = "disable"
```
I have setup multiple validators, and blocks are being produced normally.

Is there something wrong in my configuration?

Thanks a lot

**Comment by alexanderbez** [comment]
@steevi, the configuration looks fine. What version of Juno are you using and what network are you connected to? Note, Juno currently only supports SDK v0.37.x/Tendermint v0.32.x.

**Comment by steevi** [comment]
> @steevi, the configuration looks fine. What version of Juno are you using and what network are you connected to? Note, Juno currently only supports SDK v0.37.x/Tendermint v0.32.x.

Thanks a lot @alexanderbez. I'm using SDK 0.34.4 (wich is an issue!) and tendermint 0.33. Will juno work with tendermint 0.33? Or should i revert to 0.32.x?

Also, I'm using the juno version from master branch

Thanks a lot

**Comment by alexanderbez** [comment]
Yes, it will. Check out https://github.com/fissionlabsio/juno#versions.

> Also, I'm using the juno version from master branch

You cannot use master against an 0.34.x chain. I recommend using v0.0.2 if you're running again an 0.34.x chain.
